# Generated by Django 5.0.7 on 2024-07-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.states'),
        ),
    ]
